    <div class="header-main">
        <div class="container">
            <div class="header-search">
                <div class="header-search-form">
                    <i class="header-search-icon jsHeaderSeachIcon">
                        <svg class="icon search" viewBox="0 0 32 32">
                            <use xlink:href="#icon-search"></use>
                        </svg>
                    </i>
                    <div class="header-search-input jsHeaderSeachInput">
                        <input type="text" placeholder="SEARCH">
                    </div>
                </div>
            </div>
            <a href="home-page.html" class="header-logo">
                <svg class="icon main-logo">
                    <use xlink:href="#aigner-logo"></use>
                </svg>
                <svg class="icon main-emblem">
                    <use xlink:href="#aigner-emblem"></use>
                </svg>
            </a>
            <div class="header-menu">
                <a href="login-register-page.html" class="header-menu-link">
                    <span>Login - Register</span>
                    <svg class="icon account">
                        <use xlink:href="#icon-account"></use>
                    </svg>
                </a>
                <a href="my-reservation-page.html" class="header-menu-link">
                    <span>Reservation</span>
                    <svg class="icon cart">
                        <use xlink:href="#icon-cart"></use>
                    </svg>
                </a>
                <div class="header-menu-mobile jsHeaderMenuMobile">
                    <span class="lines"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="header-nav">
        <div class="container jsHeaderNavContainer">
            <div class="header-nav-item jsHeaderNavItem">
                <a href="product-listing-page.html" class="header-nav-link">Women</a>
                <div class="header-submenu">
                    <div class="container">
                        <div class="header-submenu-list">
                            <a href="product-listing-page.html" class="header-submenu-link">Bags</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Belts</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Wallets</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Keychains &amp; Key cases</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Leather accessories</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Foulards</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Fashion</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Watches</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Shoes</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Sunglasses</a>
                        </div>
                    </div>

                </div>
            </div>
            <div class="header-nav-item jsHeaderNavItem">
                <a href="product-listing-page.html" class="header-nav-link">Men</a>
                <div class="header-submenu">
                    <div class="container">
                        <div class="header-submenu-list">
                            <a href="product-listing-page.html" class="header-submenu-link">Bags</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Belts</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Wallets</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Keychains &amp; Key cases</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Leather accessories</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Foulards</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Sunglasses</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Shoes</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Watches</a>
                            <a href="product-listing-page.html" class="header-submenu-link">Fashion</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header-nav-item jsHeaderNavItem">
                <a href="#" class="header-nav-link">Magazine</a>
                <div class="header-submenu">
                    <div class="container">
                        <div class="header-submenu-list">

                        </div>
                    </div>
                </div>
            </div>
            <div class="header-nav-item jsHeaderNavItem">
                <a href="#" class="header-nav-link">Inspiration</a>
                <div class="header-submenu">
                    <div class="container">
                        <div class="header-submenu-list">
                            <a href="#" class="header-submenu-link">Videos</a>
                            <a href="#" class="header-submenu-link">Keylooks</a>
                            <a href="#" class="header-submenu-link">Season Highlights</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>