<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php 
	$_menu = $block->getHtml('level-top', 'submenu', $columnsLimit);
	$helperCustId = $this->helper(\Trans\Gtm\Helper\Data::class); 
    $getCustomerId = (!$helperCustId->getCustomerIdCustom()) ? 'Not Login yet' : $helperCustId->getCustomerIdCustom() ;
?>

<nav class="navigation" id="navigationIdCustom" data-action="navigation" data-customerid="<?=$getCustomerId?>">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul>
</nav>
