<?php
/**
 * @category Trans
 * @package  Magento_Customer
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author	Babono <babono@transdigital.co.id?
 *
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<div class="form-block">
    <div class="form-head">Forgot Password</div>
    <div class="form-block-wrapper">
        <form class="form password forget"
            action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
            method="post"
            id="form-validate"
            data-mage-init='{"validation":{}}'>
            <div class="form-group field email required">
                <div class="form-label">Email Address *</div>
                <div class="form-input">
                    <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
            <?= $block->getChildHtml('form_additional_info') ?>
            <div class="form-action">
                <button type="submit" class="btn">Submit</button>
            </div>
        </form>
    </div>
</div>
