<?php
/**
 * @author   J.P <jaka.pondan@transdigital.co.id>
 *
 * Copyright © 2019 PT Trans Digital. All rights reserved.
 * http://www.ctcorpora.com
 */
?>
<style>
section {
    margin-bottom: 40px;
    display: block;
}
#latest-post .row {
    display: flex;
    margin: 0;
}
.clearfix:after {
    display: block;
    content: ".";
    clear: both;
    font-size: 0;
    line-height: 0;
    height: 0;
    overflow: hidden;
}
#latest-post .col {
    border-left-width: 0;
}
.span_7 {
    width: 58.3333333333%;
    border-left-width: 5px;
    padding: 0;
    margin-left: 0;
}
.col {
    border: 0 solid rgba(0,0,0,0);
    float: left;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    -ms-box-sizing: border-box;
    -o-box-sizing: border-box;
    box-sizing: border-box;
    -moz-background-clip: padding-box !important;
    -webkit-background-clip: padding-box !important;
    background-clip: padding-box !important;
}

a {
    color: #222;
    text-decoration: none;
}
#latest-post img {
    display: block;
    width: 100%;
    height: 100%;
    object-fit: cover;
}
a img {
    border: none;
}
#latest-post .latest-post-text {
    position: relative;
    padding: 40px;
    background: #bbb;
}
#latest-post .col {
    border-left-width: 0;
}
.span_5 {
    width: 41.6666666667%;
    border-left-width: 5px;
    padding: 0;
    margin-left: 0;
}

#latest-post .latest-post-header {
    text-transform: uppercase;
}
p {
    line-height: 1.6;
}

#latest-post a {
    -webkit-transition: -webkit-all .15s ease;
    -moz-transition: -moz-all .15s ease;
    -ms-transition: -ms-all .15s ease;
    -o-transition: -o-all .15s ease;
    transition: all .15s ease;
    color: #222 !important;
    text-decoration: none;
}

#latest-post .latest-post-title {
    margin: 15px 0 40px;
    text-transform: uppercase;
    font-size: 24px;
    text-decoration:none;
}
p {
    line-height: 1.6;
}
#latest-post .latest-post-summary {
    padding-bottom: 35px;
}
#latest-post #read-more-link {
    position: absolute;
    bottom: 40px;
    text-decoration: underline;
}
</style>
<section id="latest-post">
    <div class="row clearfix">
        <div class="latest-post-image col span_7">
            <a href="https://www.aignermunich.com/blog/aigner-blog-savona-bag-enlightenment-fw19/">
                <picture>
                    <source media="(max-width: 767px)" srcset="https://res.cloudinary.com/dauflo55h/image/upload/f_auto,q_auto:eco,c_pad,b_white,d_ph.gif,w_757/blog/new/AIGNERMAGAZIN-Savona-Bag-Enlightenment-KATE-GELINSKY-B.jpg,
                                                https://res.cloudinary.com/dauflo55h/image/upload/f_auto,q_auto:eco,c_pad,b_white,d_ph.gif,w_1514/blog/new/AIGNERMAGAZIN-Savona-Bag-Enlightenment-KATE-GELINSKY-B.jpg 2x">
                    <source media="(max-width: 1024px)" srcset="https://res.cloudinary.com/dauflo55h/image/upload/f_auto,q_auto:eco,c_pad,b_white,d_ph.gif,w_670/blog/new/AIGNERMAGAZIN-Savona-Bag-Enlightenment-KATE-GELINSKY-B.jpg,
                                                https://res.cloudinary.com/dauflo55h/image/upload/f_auto,q_auto:eco,c_pad,b_white,d_ph.gif,w_1340/blog/new/AIGNERMAGAZIN-Savona-Bag-Enlightenment-KATE-GELINSKY-B.jpg 2x">
                    <img srcset="https://res.cloudinary.com/dauflo55h/image/upload/f_auto,q_auto:eco,c_pad,b_white,d_ph.gif,w_1492/blog/new/AIGNERMAGAZIN-Savona-Bag-Enlightenment-KATE-GELINSKY-B.jpg 2x" src="https://res.cloudinary.com/dauflo55h/image/upload/f_auto,q_auto:eco,c_pad,b_white,d_ph.gif,w_746/blog/new/AIGNERMAGAZIN-Savona-Bag-Enlightenment-KATE-GELINSKY-B.jpg">
                </picture>
            </a>
        </div>
        <div class="latest-post-text col span_5">
            <p class="latest-post-header">Magazine</p>
            <a href="https://www.aignermunich.com/blog/aigner-blog-savona-bag-enlightenment-fw19/">
                <p class="latest-post-title">Savona – The Feel Good Bag</p>
            </a>
            <p class="latest-post-summary">Savona – The Feel Good Bag
            Life is as colorful as you can imagine. And even though you may favor modest basics, do you still look for that certain something? Very good, then I have a new bag for you! AIGNER’s Savona Bag is one of the bags you can really wear all the time. I call this kind of handbag &amp;ldq…</p>
            <a id="read-more-link" href="https://www.aignermunich.com/blog/aigner-blog-savona-bag-enlightenment-fw19/">Read article</a>
        </div>
    </div>
</section>