<?php
/**
 * @category Trans
 * @package  Trans_Blog
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author   Babono <nurul.akbar@transdigital.co.id>
 *
 * This a Mageplaza Blog Module overiding
 *
 * Copyright © 2019 PT Trans Digital. All rights reserved.
 * http://www.ctcorpora.com
 */

/** @var \Mageplaza\Blog\Block\Frontend $block */
?>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $(window).load(function () {
            var body = $('body');

            if (body.hasClass('page-layout-1column')) {
                $('.columns').find('.sidebar.sidebar-main').remove();
            }
            <?php if ($block->getCurrentTheme() == "Etheme/yourstore") :?>
            body.addClass('mpblog-etheme-yourstore');
            <?php endif; ?>
        });
    });
</script>

<?php $color = $block->getHelper()->getBlogConfig('general/font_color'); ?>
<style type="text/css">
    #mpblog-list-container a {
        text-decoration: none;
    }

    .breadcrumbs{
        display: none;
    }

    .page-title-wrapper{
        display: none;
    }

    .mp-footer{
        display: none;
    }

    #blog-topics{
        position: absolute;
        top: 100px;
        right: 5px;
        font-size: 16px;
        text-transform: uppercase;
    }

    #blog-topics p {
        position: relative;
        margin-bottom: 20px;
    }

    #blog-topics ul {
        list-style: none;
        margin: 0;
        padding: 0;
    }

    .page-layout-2columns-right .column.main{
        width: 100%;
    }

    /*Post List Content Css*/
    .post-info-wraper h2.mp-post-title a,
    .about-admin h4.admin-title a,
    .mp-post-meta-info a.mp-read-more,
    .mp-post-info a.mp-info,
    ul.menu-categories a.list-categories:hover,
    .products-same-post a.product-item-link:hover,
    a.mp-relate-link,
    .mpblog-product-name {
        color: <?= $color ?> !important;
    }

    a.label.label-default.tags-list:hover,
    a.label.label-default.tags-list:focus {
        background: <?= $color ?>;
        color: #fff !important;
    }

    .list-post-tabs a {
        background: #fbfbfb;
        color: <?= $color ?>;
    }

    /*Site Map CSS*/
    .mp-sidebar a.sitemap-link,
    .menu-archives a.list-archives:hover {
        text-decoration: none !important;
        color: <?= $color ?> !important;
    }

    /*Comment CSS*/
    button.default-cmt__content__cmt-block__cmt-box__cmt-btn__btn-submit {
        background: <?= $color ?> !important;
        color: #fff;
        border-color: #999 !important;
    }

    span.cmt-row__cmt-username {
        font-weight: 600;
        color: <?= $color ?>;
    }

    a.interactions__btn-actions.mpblog-like {
        color: #333333
    }

    a.interactions__btn-actions.mpblog-liked {
        color: <?= $color ?>;
    }

    a.interactions__btn-actions {
        color: <?= $color ?>;

    }

    /*Widget CSS*/
    .widget-title a {
        color: <?= $color ?>;
        font-size: 26px;
    }

    /*Author CSS*/
    .author-name h3 {
        color: <?= $color ?>;
        text-align: center;
    }
</style>

