<?php
/**
 * @author   hadi <ashadi.sejati@transdigital.co.id>
 *
 * Copyright © 2019 PT Trans Digital. All rights reserved.
 * http://www.ctcorpora.com
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="additional-attributes-wrapper table-wrapper">
        <div class="title-specs-att"><span><?= /* @escapeNotVerified */ __('PRODUCT DETAILS') ?></span></div>
        <ul id="product-attribute-specs-table">
            <?php
                $attributesNews = explode("|", strip_tags($_product->getDescription()));
                foreach ($attributesNews as $attributesNew) {
                    echo '<li>'.$attributesNew.'</li>';
                }
            ?>
        </ul>

    </div>
<?php endif;?>
