<form class="form form-edit-account change-password" action="<?= $block->escapeUrl($block->getUrl('customer/account/changePasswordPost')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Edit Your Password')) ?></span></legend>
    </fieldset>
    <fieldset class="fieldset password" data-container="change-email-password">
        <div class="field password current required">
            <label class="label" for="current-password"><span><?= $block->escapeHtml(__('Current Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password"
                       data-input="current-password"
                       data-validate="{required:true}"
                       autocomplete="off" />
            </div>
        </div>
        <div class="field new password required" data-container="new-password">
            <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                       data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                       data-input="new-password"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirm password required" data-container="confirm-password">
            <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                       data-input="confirm-password"
                       data-validate="{required:true}"
                       autocomplete="off" />
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="btn-cancel">
            <a title="<?= $block->escapeHtmlAttr(__('Cancel')) ?>" href="<?= $block->getBackUrl() ?>"><span><?= $block->escapeHtml(__('Cancel')) ?></span></a>
        </div>
        <div class="btn-primary">
            <button type="submit" class="btn" title="<?= $block->escapeHtmlAttr(__('Save')) ?>"><span><?= $block->escapeHtml(__('Save Changes')) ?></span></button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
