<?php 
/**
 * @category Trans
 * @package  Magento_Customer
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 *
 * @author   hadi <ashadi.sejati@transdigital.co.id>
 *
 * Copyright © 2019 PT Trans Digital. All rights reserved.
 * http://www.ctcorpora.com
 */


?>

<div class="block block-addresses-default block-addresses-default-c">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Address Book')) ?></strong></div>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="button" role="add-address" title="<?= $block->escapeHtmlAttr(__('Add New Address')) ?>" class="action primary add"><span><?= $block->escapeHtml(__('Add New Address')) ?></span></button>
        </div>
    </div>
</div>
