<?php 
/**
 * @category Trans
 * @package  Magento_Customer
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 *
 * @author   hadi <ashadi.sejati@transdigital.co.id>
 *
 * Copyright © 2019 PT Trans Digital. All rights reserved.
 * http://www.ctcorpora.com
 */
?>
<div class="block block-dashboard-info-name">
    <div class="block-content">
        Hello, <?= $block->escapeHtml($block->getName()) ?>!
    </div>
</div>
