<?php
/**
 * @category Trans
 * @package  Magento_Customer
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 *
 * @author   hadi <ashadi.sejati@transdigital.co.id>
 *
 * Copyright © 2019 PT Trans Digital. All rights reserved.
 * http://www.ctcorpora.com
 */
?>
<div class="block block-dashboard-info">
    <div class="block-title" style="display: none;"><strong><?= $block->escapeHtml(__('Account Information')) ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Contact Information')) ?></span>
                <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                    <span><?= $block->escapeHtml(__('Edit')) ?></span>
                </a>
            </strong>
            <div class="box-content">
                <p>
                    <?= $block->escapeHtml($block->getName()) ?><br>
                    <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?><br>
                    <?= $block->escapeHtml($block->getTelephone()) ?><br>
                </p>
                <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
            </div>
        </div>
        <div class="box box-password">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Change Password')) ?></span>
                <a class="action edit" href="<?= $block->escapeUrl($block->getCustomChangePasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
            </strong>
            <div class="box-content">
                <p>*****************</p>
            </div>
        </div>
    </div>
</div>
