<?php
/**
 * Copyright © 2021 CT Corp Digital. All rights reserved.
 * https://www.ctcorpdigital.com
 *
 * @category Trans
 * @package  Trans_Reservation
 * @license  Proprietary
 *
 * @author   Imam Kusuma <imam.kusuma@ctcorpdigital.com>
 * @author   Edi Suryadi <edi.suryadi@ctcorpdigital.com>
 */

/*** @var $block \Magento\Catalog\Block\Product\ListProduct */

$productCollection = $block->getLoadedProductCollection();
$helper = $this->helper('Magento\Catalog\Helper\Output');
$transProductHelper = $this->helper('Trans\Catalog\Helper\Product');
$gtmHelper = $this->helper('Trans\Gtm\Helper\Data');
$getCustomerId = $gtmHelper->getCurrentCustomerId();
?>
<?php if (!$productCollection || !$productCollection->count()): ?>
    <div class="message info empty">
        <div><?= /* @escapeNotVerified */ __('SORRY, NO PRODUCTS FOUND') ?></div>
        <div><?= /* @escapeNotVerified */ __('We\'re sorry that we couldn\'t find any products matching, please make sure that you have entered the correct search term and try again.') ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */
            $counter = 1;
            ?>

            <?php foreach ($productCollection as $_product): ?>
                <?php //$product = $helper->productAttribute($_product, $_product->getId(), 'id'); ?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" id="productList<?=$counter?>" tabindex="-1"
                        onclick="dataLayer.push({
                        'event': 'product_click',
                        'product_size': '<?= $gtmHelper->getProductAttributeValue($_product->getId(), 'size'); ?>',
                        'product_for': '<?= $gtmHelper->getCategoryC0NamesByProduct($_product) ?>',
                        'user_id': '<?= $getCustomerId ?>',
                        'ecommerce': {
                          'click': {
                            'actionField': {'list': 'Shop'},
                            'products': [{
                              'name': '<?= /* @escapeNotVerified */ $helper->productAttribute($_product, $_product->getName(), 'name') ?>',
                              'id': '<?= /* @escapeNotVerified */ $helper->productAttribute($_product, $_product->getSku(), 'sku') ?>',
                              'price': '<?= /* @escapeNotVerified */ $helper->productAttribute($_product, $_product->getFinalPrice(), 'price') ?>',
                              'brand': 'Aigner',
                              'category': '<?= $gtmHelper->getCategoryNamesByProduct($_product) ?>',
                              'variant': '<?= $gtmHelper->getProductAttributeValue($_product->getId(), 'color'); ?>',
                              'position': '<?=$counter?>'
                             }]}}});
                        "
                         data-layer-already="0">

                        <?= $productImage->toHtml() ?>
                    </a>
                    <span class="datalayer-click" style="display: none;" onclick='dataLayer.push({"event": "product_view","product_size": "<?= $gtmHelper->getProductAttributeValue($_product->getId(), 'size'); ?>","product_for": "<?= $gtmHelper->getCategoryC0NamesByProduct($_product) ?>","user_id": "<?=$getCustomerId?>","ecommerce": {"currencyCode": "IDR","impressions": [{"name": "<?=$helper->productAttribute($_product, $_product->getName(), 'name') ?>","sku": "<?=$helper->productAttribute($_product, $_product->getSku(), 'sku') ?>","price": "<?=$helper->productAttribute($_product, $_product->getFinalPrice(), 'price') ?>","brand": "Aigner","category": "<?= $gtmHelper->getCategoryNamesByProduct($_product) ?>","variant": "<?= $gtmHelper->getProductAttributeValue($_product->getId(), 'color'); ?>","list": "Shop","position": "<?=$counter?>"}]}});'></span>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?php if($badgeHtml = $transProductHelper->getProductBadge($_product)): ?>
                            <div class="product-badge-container"><?= $badgeHtml ?></div>
                        <?php else : ?>
                            <div class="product-badge-container"></div>
                        <?php endif; ?>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable() && !$block->isDisableSales()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </li>
            <?php $counter++; endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
    require([
    'jquery',
    'domReady!'
], function ($) {
    function isOnScreen(elem) {
        // if the element doesn't exist, abort
        if( elem.length == 0 ) {
            return;
        }
        var $window = $(window)
        var viewport_top = $window.scrollTop()
        var viewport_height = $window.height()
        var viewport_bottom = viewport_top + viewport_height
        var $elem = $(elem)
        var top = $elem.offset().top
        var height = $elem.height()
        var bottom = top + height

        return (top >= viewport_top && top < viewport_bottom) ||
        (bottom > viewport_top && bottom <= viewport_bottom) ||
        (height > viewport_height && top <= viewport_top && bottom >= viewport_bottom)
    }

    $(window).on('scroll', function() {
        $(".product-items .product-item .product").each(function(){
            var idData = '#' + $(this).attr('id');
            if( isOnScreen( $(idData) ) ) {
                if ($(this).attr('data-layer-already') == 0) {
                    $(this).next('span.datalayer-click').click();
                    $(this).attr('data-layer-already','1');
                }
            }
        });
    });
    $(".product-items .product-item .product").each(function(){
        var idData = '#' + $(this).attr('id');
        if( isOnScreen( $(idData) ) ) {
            if ($(this).attr('data-layer-already') == 0) {
                $(this).next('span.datalayer-click').click();
                $(this).attr('data-layer-already','1');
            }
        }
    });

});
</script>
