<?php
/**
 * @author   hadi <ashadi.sejati@transdigital.co.id>
 *
 * Copyright © 2019 PT Trans Digital. All rights reserved.
 * http://www.ctcorpora.com
 */


// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Register $block */
?>
<?php if($block->getPageTitle()): ?>
<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper"></span><?= $block->getPageTitle() ?></span>
    </h1>
</div>
<?php endif; ?>
