<?php
/**
 * @category Trans
 * @package  Trans_Blog
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 * @author   Babono <nurul.akbar@transdigital.co.id>
 * @author   Ilma Dinnia Alghani <ilma.dinnia@transdigital.co.id>
 *
 * This a Mageplaza Blog Module overiding
 *
 * Copyright © 2019 PT Trans Digital. All rights reserved.
 * http://www.ctcorpora.com
 */

use Mageplaza\Blog\Model\Config\Source\Comments\Type;

/** @var \Mageplaza\Blog\Block\Post\View $block */

/** @var \Mageplaza\Blog\Helper\Data $helper */
$helper = $this->helper(\Mageplaza\Blog\Helper\Data::class);

$_post = $block->getPost();

$author = $helper->getAuthorByPost($_post);
$authorName = $author !== null ? $author->getName() : '';

$modifier = $helper->getAuthorByPost($_post, true);
$modifierName = $modifier !== null ? $modifier->getName() : '';
$isLogged = ($block->isLoggedIn()) ? 'Yes' : 'No';
$color = $helper->getBlogConfig('general/font_color');
$helperCustId = $this->helper(\Trans\Gtm\Helper\Data::class); 
$getCustomerId = (!$helperCustId->getCustomerIdCustom()) ? 'Not Login yet' : $helperCustId->getCustomerIdCustom();
?>
<section class="blog">
    <div class="page-content">
        <div class="page-main">
            <div class="blog-article">
                <div class="blog-article-hero" style="background-image: url(<?= $block->getImageUrl($_post->getImage()); ?>)"></div>
                <div class="blog-article-post">
                    <article class="blog-article-detail">
                        <div class="blog-article-title"><a class="post-link-title" title="<?= $block->escapeHtml($_post->getName()); ?>" href="<?= $_post->getUrl() ?>">
                                <?= $_post->getName(); ?>
                            </a></div>
                        <div class="blog-article-meta">Collections •
                            <?= $block->getDateFormat($_post->getPublishDate()); ?>
                        </div>
                        <div class="blog-article-content">
                            <?= $block->getPageFilter($_post->getPostContent()); ?>
                        </div>
                        <span class="back-link">
                            <a href=" <?php echo $block->getUrl('blog.html'); ?>">
                                Back to all topics </a>
                        </span>
                    </article>
                    <div class="productRecommendation">
                        <?php if ($helper->getBlogConfig('product_post/post_detail/enable_product')) : ?>
                        <?php $relatedBlock = $block->getChildBlock('related_products'); ?>
                        <?php if ($relatedBlock->hasProduct()) : ?>
                        <div class="block-blog-related products-same-post page-products mpcss">
                            <h2>
                                <?= ($helper->getBlogConfig('product_post/post_detail/title')) ?: __('Related Products') ?>
                            </h2>
                            <div class="related-content-container">
                                <?= $relatedBlock->toHtml(); ?>
                            </div>
                        </div>
                        <?php endif; ?>
                        <?php endif; ?>
                    </div>
                    <div class="blog-recommendation">
                        <?php $relatedPosts = $_post->getRelatedPostsCollection(); ?>
                        <?php if ($relatedPosts && sizeof($relatedPosts)) : ?>
                        <div class="blog-recommendation-head">
                            <?= __('You May Also Like These Posts'); ?>
                        </div>
                        <div class="blog-recommendation-list">
                            <div class="blog-recommendation-item">
                                <?php foreach ($relatedPosts as $post) : ?>
                                <div style="display: flex;">
                                    <div class="blog-recommendation-image">
                                        <?php if ($post->getImage()) : ?>
                                        <a href="<?= $post->getUrl() ?>">
                                            <img class="img-responsive" src="<?= $block->resizeImage($post->getImage(), '400x'); ?>" alt="<?= $block->escapeHtml($post->getName()); ?>" />
                                        </a>
                                        <?php endif; ?>
                                    </div>
                                    <div class="post-info-wraper">
                                        <h2 class="mp-post-title">
                                            <a class="post-link-title" title="<?= $block->escapeHtml($post->getName()); ?>" href="<?= $post->getUrl() ?>">
                                                <?= $post->getName(); ?>
                                            </a>
                                        </h2>
                                        <div class="mp-post-info">
                                            <?= $block->getPostInfo($post); ?>
                                        </div>
                                    </div>
                                </div>
                                <?php endforeach; ?>
                                <div class="mp-clear"></div>
                            </div>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
        <?php if ($helper->getSeoConfig('snippet/enabled')) : ?>
        <?php
        $logo = $helper->getSeoConfig('snippet/upload_image_id');
        $logo = $logo ? $helper->getImageHelper()->getMediaUrl($logo) : $block->getDefaultImageUrl();
        ?>
        <script type="application/ld+json">
        {
            "@context": "http://schema.org",
            "@type": "NewsArticle",
            "mainEntityOfPage": {
                "@type": "WebPage",
                "@id": "https://google.com/article"
            },
            "headline": "<?= $_post->getName(); ?>",
            "image": {
                "@type": "ImageObject",
                "url": "<?= $_post->getImage() ? $block->getImageUrl($_post->getImage()) : $block->getDefaultImageUrl(); ?>",
                "height": 800,
                "width": 800
            },
            "datePublished": "<?= $block->getDateFormat($_post->getPublishDate()); ?>",
            "dateModified": "<?= $block->getDateFormat($_post->getUpdatedAt()); ?>",
            "author": {
                "@type": "Person",
                "name": "<?= $authorName; ?>"
            },
            "publisher": {
                "@type": "Organization",
                "name": "<?= $helper->getSeoConfig('snippet/organize_name'); ?>",
                "logo": {
                    "@type": "ImageObject",
                    "url": "<?= $logo; ?>",
                    "width": 600,
                    "height": 60
                }
            },
            "description": "<?= $_post->getShortDescription(); ?>"
        }
        </script>
        <?php endif; ?>
        <!-- data layer -->
        <script>
        require(['jquery'], function($) {
            $(document).ready(function() {
                var textArticle = $(".blog-article-content").text().trim();
                var countArticle = textArticle.length;
                dataLayer.push({
                    'event': 'article_engagement',
                    'content_title': '<?= $_post->getName(); ?>',
                    'content_source': 'aignermunich',
                    'content_category': 'Collections',
                    'content_type': 'standart',
                    'content_length': countArticle,
                    'content_publishedDate': '<?= $this->getDateFormat($_post->getPublishDate())?>',
                    'user_id': '<?=$getCustomerId?>'
                });

            });
        });
        </script>
</section>