<?php
/**
 * @category Trans
 * @package  Trans_ProductRelation
 * @license  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 *
 * @author   Imam Kusuma <imam.kusuma@ctcorpdigital.com>
 *
 * Copyright © 2019 PT Trans Digital. All rights reserved.
 * http://www.ctcorpora.com
 */

// @codingStandardsIgnoreFile

/* @var $block \Trans\ProductRelation\Block\Product\List\Combinations */
?>

<?php
if ($exist = $block->getItems()->getSize()) {
    $type = 'combinations';
    $class = $type;

    $image = 'related_products_list';
    $title = __('Suitable Combinations');
    $items = $block->getItems();
    $limit = 0;
    $shuffle = 0;
    $canItemsAddToCart = $block->canItemsAddToCart();

    $templateType = null;
    $description = false;
}
$getCustomerId = (!$block->getCustomerIdCustom()) ? 'Not Login yet' : $block->getCustomerIdCustom();
?>

<?php if ($exist):?>

    <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
    <div class="block-title title">
        <strong id="block-<?= /* @escapeNotVerified */ $class ?>-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?= /* @escapeNotVerified */ $class ?>-heading">
        <?php if ($type == 'related' && $canItemsAddToCart): ?>
        <div class="block-actions">
            <?= /* @escapeNotVerified */ __('Check items to add to the cart or') ?>
            <button type="button" class="action select" role="select-all"><span><?= /* @escapeNotVerified */ __('select all') ?></span></button>
        </div>
        <?php endif; ?>
        <div class="products wrapper grid products-grid products-<?= /* @escapeNotVerified */ $type ?>">
            <ol class="products list items product-items">
                <?php $counter = 1; foreach ($items as $_item): ?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable()): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php 
                    $product = $block->getProductById($_item->getId()); 
                    $categoryIds = $product->getCategoryIds();
                    $categories = $block->getCategoryCollection()->addAttributeToFilter('entity_id', $categoryIds);
                    $categoryName = '';
                    $categoryNameParent = '';
                    $i = 1;
                    foreach ($categories as $category) {
                        if ($i==1) {
                            $categoryName .= $category->getName();
                            $categoryNameParent .= $category->getParentCategory()->getName();
                        }
                        else {
                            $categoryName .= ','.$category->getName();
                            $categoryNameParent .= ','.$category->getParentCategory()->getName();
                        }
                        $i++;
                    }
                ?>
                <li class="item product product-item">
                    <div class="product-item-info <?= /* @escapeNotVerified */ $available ?>">
                    <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
                    <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo"
                        onclick="dataLayer.push({
                        'event': 'productView_suitable',
                        'product_size': '<?= $_item->getResource()->getAttribute('size')->getFrontend()->getValue($_item); ?>',
                        'product_for': '<?=$categoryNameParent?>',
                        'user_id': '<?=$getCustomerId?>',
                      'ecommerce': {
                        'currencyCode': 'IDR',
                        'impressions': [
                         {
                           'name': '<?= $block->escapeHtml($_item->getName()) ?>',
                           'id': '<?= $_item->getId() ?>',
                           'price': '<?= $_item->getPrice() ?>',
                           'brand': 'Aigner',
                           'category': '<?=$categoryName?>',
                           'variant': '<?= $_item->getResource()->getAttribute('color')->getFrontend()->getValue($_item); ?>',
                           'list': 'Shop',
                           'position': '<?=$counter?>'
                         }]}});
                        dataLayer.push({
                        'event': 'productClick_suitable',
                        'product_size': '<?= $_item->getResource()->getAttribute('size')->getFrontend()->getValue($_item); ?>',
                        'product_for': '<?=$categoryNameParent?>',
                        'user_id': '<?=$getCustomerId?>',
                        'ecommerce': {
                          'click': {
                            'actionField': {'list': 'Suitable Combinations'},
                            'products': [{
                              'name': '<?= $block->escapeHtml($_item->getName()) ?>',
                              'id': '<?= $_item->getId() ?>',
                              'price': '<?= $_item->getPrice() ?>',
                              'brand': 'Aigner',
                              'category': '<?=$categoryName?>',
                              'variant': '<?= $_item->getResource()->getAttribute('color')->getFrontend()->getValue($_item); ?>',
                              'position': '<?=$counter?>'
                             }]}}});
                        ">
                        <?php echo $block->getImage($_item, $image)->toHtml() ?>
                    </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                                <?= $block->escapeHtml($_item->getName()) ?></a>
                            </strong>

                            <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>

                            <?php if ($templateType): ?>
                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <div class="field choice related">
                                        <input type="checkbox" class="checkbox related" id="related-checkbox<?= /* @escapeNotVerified */ $_item->getId() ?>" name="related_products[]" value="<?= /* @escapeNotVerified */ $_item->getId() ?>" />
                                        <label class="label" for="related-checkbox<?= /* @escapeNotVerified */ $_item->getId() ?>"><span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span></label>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </li>
                <?php $counter++; endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif;?>
