<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
<!-- <a class="logo" href="" title="<?= /* @escapeNotVerified */ $storeName ?>">
    <img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
         title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
         alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
         <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
         <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
    />
</a> -->
<a href="<?= $block->getUrl('') ?>" class="header-logo">
    <svg class="icon main-logo">
        <use xlink:href="#aigner-logo"></use>
    </svg>
    <svg class="icon main-emblem">
        <use xlink:href="#aigner-emblem"></use>
    </svg>
</a>
