<?php

 /**
 * Copyright © 2021 CT Corp Digital. All rights reserved.
 * https://www.ctcorpdigital.com
 *
 * @category CTCD
 * @package  CTCD_Core
 * @license  Proprietary
 *
 * @author   Ashadi Muliawan <ashadi.sejati@ctcorpdigital.com>
 */

?>

<form method="post" action="" id="login-form" data-mage-init='{"form": {}, "validation": {}}' autocomplete="off">
    <fieldset class="admin__fieldset">
        
        <input name="form_key" type="hidden" value="<?= /* @escapeNotVerified */ $block->getFormKey() ?>" />
        <div class="admin__field _required field-username">
            <label for="username" class="admin__field-label">
                <span><?= /* @escapeNotVerified */ __('Username') ?></span>
            </label>
            <div class="admin__field-control">
                <input id="username"
                       class="admin__control-text"
                       type="text"
                       name="login[username]"
                       autofocus
                       value=""
                       data-validate="{required:true}"
                       placeholder="<?= /* @escapeNotVerified */ __('user name') ?>"
                       autocomplete="off"
                    />
            </div>
        </div>
        <div class="admin__field _required field-password">
            <label for="login" class="admin__field-label">
                <span><?= /* @escapeNotVerified */ __('Password') ?></span>
            </label>
            <div class="admin__field-control">
                <input id="login"
                       class="admin__control-text"
                       type="password"
                       name="login[password]"
                       data-validate="{required:true}"
                       value=""
                       placeholder="<?= /* @escapeNotVerified */ __('password') ?>"
                       autocomplete="off"
                    />
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
        <div class="form-actions">
            <?= $block->getChildHtml('form.buttons') ?>
        </div>
    </fieldset>
</form>
