<?php
/**
 * Copyright © 2021 CT Corp Digital. All rights reserved.
 * https://www.ctcorpdigital.com
 *
 * @category Trans
 * @package  Trans_Widgets
 * @license  Proprietary
 *
 * @author   HaDi <ashadi.sejati@ctcorpdigital.com>
 * @author   Edi Suryadi <edi.suryadi@ctcorpdigital.com>
 */
?>
<section class="latest-post">
    <div class="row clearfix">
        <?php if($post = $block->getLatestPost()): ?>
            <div class="latest-post-image col span_7">
                <a href="<?= $post->getUrl() ?>">
                    <picture>
                        <img src="<?= $block->resizeImage($post->getImage(), '1200x'); ?>" alt="<?= $block->escapeHtml($post->getName()); ?>"/>
                    </picture>
                </a>
            </div>
            <div class="latest-post-text col span_5">
                <p class="latest-post-header"><?= $block->getData('title'); ?></p>
                <a href="<?= $post->getUrl() ?>">
                    <p class="latest-post-title"><?= $post->getName(); ?></p>
                </a>
                <p class="latest-post-summary"><?= $block->maxShortDescription($post->getShortDescription()); ?></p>
                <a id="read-more-link" href="<?= $post->getUrl() ?>"><?= __('Read article') ?></a>
            </div>
        <?php endif; ?>
    </div>
</section>
