<?php
/**
 * Copyright © 2021 CT Corp Digital. All rights reserved.
 * https://www.ctcorpdigital.com
 *
 * @category Trans
 * @package  Trans_Reservation
 * @license  Proprietary
 *
 * @author   Imam Kusuma <imam.kusuma@ctcorpdigital.com>
 * @author   Edi Suryadi <edi.suryadi@ctcorpdigital.com>
 */

 /* @var $block Trans\Reservation\Block\Product\View\ReservationPopup */
?>

<div id="popup" style="display: none;">
	<div id="reservation-list">
	</div>
</div>
