<?php

 /**
 * Copyright © 2021 CT Corp Digital. All rights reserved.
 * https://www.ctcorpdigital.com
 *
 * @category CTCD
 * @package  CTCD_Core
 * @license  Proprietary
 *
 * @author   Ashadi Muliawan <ashadi.sejati@ctcorpdigital.com>
 */

?>
<a class="link-copyright" href="https://ctcorpdigital.com/" target="_blank" title="<?= /* @escapeNotVerified */ __('CT Corp Digital') ?>">
	<img src="<?php echo $this->getViewFileUrl('CTCD_Core::images/ctcd-powered-logo.png'); ?>" />
</a>
