<?php

/**
 * Copyright © 2021 CT Corp Digital. All rights reserved.
 * https://www.ctcorpdigital.com
 *
 * @category CTCD
 * @package  CTCD_Core
 * @license  Proprietary
 *
 * @author   Ashadi Muliawan <ashadi.sejati@ctcorpdigital.com>
 * @author   Edi Suryadi <edi.suryadi@ctcorpdigital.com>
 */

/** @var $block \Magento\Backend\Block\Page\Header */
$part = $block->getShowPart();
?>
<?php if ($part === 'logo') : ?>
        <?php $edition = $block->hasEdition() ? 'data-edition="' . $block->escapeHtml($block->getEdition()) . '"' : ''; ?>
        <?php $logoSrc = $block->escapeHtml($block->getLogoImageSrc()) ?>
        <a
            href="<?= $block->escapeUrl($block->getHomeLink()) ?>"
            <?= /* @noEscape */ $edition ?>
            class="logo">
            <?php if($block->hasLogoImageSrc()): ?>
            <img class="logo-img custom-logo" src="<?= /* @noEscape */ $logoSrc ?>"
            alt="<?= $block->escapeHtmlAttr(__($block->getLogoImageTitle())) ?>" title="<?= $block->escapeHtmlAttr($block->getLogoImageTitle()) ?>"/>
            <?php else: ?>
            <img class="logo-img" src="<?= /* @noEscape */ $block->getViewFileUrl($logoSrc) ?>"
            alt="<?= $block->escapeHtmlAttr(__('Magento Admin Panel')) ?>" title="<?= $block->escapeHtmlAttr(__('Magento Admin Panel')) ?>"/>
            <?php endif; ?>
        </a>
<?php elseif ($part === 'user') : ?>
        <div class="admin-user admin__action-dropdown-wrap">
            <a
                href="<?= /* @noEscape */ $block->getUrl('adminhtml/system_account/index') ?>"
                class="admin__action-dropdown"
                title="<?= $block->escapeHtmlAttr(__('My Account')) ?>"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown">
                <span class="admin__action-dropdown-text">
                    <span class="admin-user-account-text"><?= $block->escapeHtml($block->getUser()->getUserName()) ?></span>
                </span>
            </a>
            <ul class="admin__action-dropdown-menu">
                <?php if ($block->getAuthorization()->isAllowed('Magento_Backend::myaccount')) : ?>
                <li>
                    <a
                        href="<?= /* @noEscape */ $block->getUrl('adminhtml/system_account/index') ?>"
                        <?= /* @noEscape */ $block->getUiId('user', 'account', 'settings') ?>
                        title="<?= $block->escapeHtmlAttr(__('Account Setting')) ?>">
                        <?= $block->escapeHtml(__('Account Setting')) ?> (<span class="admin-user-name"><?= $block->escapeHtml($block->getUser()->getUserName()) ?></span>)
                    </a>
                </li>
                <?php endif; ?>
                <li>
                    <a
                        href="<?= /* @noEscape */ $block->getBaseUrl() ?>"
                        title="<?= $block->escapeHtmlAttr(__('Customer View')) ?>"
                        target="_blank" class="store-front">
                        <?= $block->escapeHtml(__('Customer View')) ?>
                    </a>
                </li>
                <li>
                    <a
                        href="<?= /* @noEscape */ $block->getLogoutLink() ?>"
                        class="account-signout"
                        title="<?= $block->escapeHtmlAttr(__('Sign Out')) ?>">
                        <?= $block->escapeHtml(__('Sign Out')) ?>
                    </a>
                </li>
            </ul>
        </div>

<?php elseif ($part === 'other') : ?>
    <?= $block->getChildHtml() ?>
<?php endif; ?>
