<?php
/**
 * @author   J.P <jaka.pondan@transdigital.co.id>
 *
 * Copyright © 2019 PT Trans Digital. All rights reserved.
 * http://www.ctcorpora.com
 */
?>
<div class="link reservecart" data-bind="scope: 'reservecart'">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?> class="reserve-cart header-menu-link">
        <span>Reservation</span>
        <svg class="icon cart">
            <use xlink:href="#icon-cart"></use>
        </svg>
    </a>
</div>
